version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: todo-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-net

  backend:
    container_name: todo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_app
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge

volumes:
  postgres_data: